name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FIELD_0D5481510 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations - Adjust these based on your project ######
          app_location: "."  # Root of your Vite app
          api_location: "api"  # Optional - leave or remove based on your project
          output_location: "dist"  # Vite build output folder
          ###### End of Repository/Build Configurations ######
        env:
          VITE_APPWRITE_URL: ${{ secrets.VITE_APPWRITE_URL }}
          VITE_APPWRITE_PROJECT_ID: ${{ secrets.VITE_APPWRITE_PROJECT_ID }}
          VITE_APPWRITE_DATABASE_ID: ${{ secrets.VITE_APPWRITE_DATABASE_ID }}
          VITE_APPWRITE_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_COLLECTION_ID }}
          VITE_APPWRITE_BUCKET_ID: ${{ secrets.VITE_APPWRITE_BUCKET_ID }}
          VITE_APPWRITE_WISHLIST_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_WISHLIST_COLLECTION_ID }}
          VITE_APPWRITE_CART_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_CART_COLLECTION_ID }}
          VITE_APPWRITE_ProductForms_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_ProductForms_COLLECTION_ID }}
          VITE_APPWRITE_OrderDetails_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_OrderDetails_COLLECTION_ID }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FIELD_0D5481510 }}
          action: "close"
